app:
  name: customer.com
  cert: "./testdata/x509/cert.pem"
  key: "./testdata/x509/key.pem"

context:
  timeout: 2

jwt:
  access_signing_key: E4IiEcW02N4N2HKWnUjA6KxwrrrJME4SrO2FHDN0CDhHUfqjDmIiAlIoXMnG9brY
  access_expiration: 5
  refresh_signing_key: KQciMyZms5nBhiEwABX9srXPVCR9PFnka3Ci3SseB4XAjBU4OTVIj1jat5oLvhCv
  refresh_expiration: 10080

dsn: "postgresql://localhost/postgres?sslmode=disable&user=postgres&password=postgres"

kafka:
  host: "localhost:9092"
  customer_group_id: "customer-consumer"
  order_group_id: "order-consumer"
  order_wal_topic: "saga.public.order"
  customer_wal_topic: "saga.public.customer"
  customer_credit_reserved_topic: "saga.customer.credit_reserved"
  customer_credit_limit_exceeded_topic: "saga.customer.credit_limit_exceeded"
